### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "Stockmanager1",
  "email": "Stockmanager1@mail.com",
  "password": "stockmanager1",
  "role":"stockmanager",
  "isUserActive":true
}

### User Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email":"Stockmanager1@mail.com",
  "password":"stockmanager1"
}

### User logout
GET http://localhost:5000/api/auth/logout



### Add Stocks
POST http://localhost:5000/api/stocks
Content-Type: application/json

{ 
  "stockSymbol":"TSLA",
  "companyName":"Tesla Inc",
  "sector":"Technology",
  "availableQuantity":560
}

### Get All Stocks
GET http://localhost:5000/api/stocks

### Delete Stock
GET http://localhost/api/stocks:TSLA


### Change password
PUT http://localhost:5000/api/auth/traders/login
Content-Type: application/json

{
  "currentPassword":"",
  "newPassword":""
}

### Get stock details
GET http://localhost:5000/api/stocks/TSLA 



### Get Stock Historical data based on days
GET http://localhost:5000/api/stocks/history/AAPL?days=30
