### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "trader101",
  "email": "trader101@mail.com",
  "password": "trader101",
  "role":"trader",
  "walletBalance":100000,
  "isUserActive":true
}

### User Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email":"trader101@mail.com",
  "password":"trader101"
}

### User logout
GET http://localhost:5000/api/auth/logout





### Change password
PUT http://localhost:5000//api/auth/traders/login
Content-Type: application/json

{
  "currentPassword":"123456",
  "newPassword":"12345"
}