### Register User
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "username": "Trader",
  "email": "Trader77@mail.com",
  "password": "123456",
  "role":"trader",
  "walletBalance":100000,
  "isUserActive":true
}

### User Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email":"Trader77@mail.com",
  "password":"123456"
}

### User logout
GET http://localhost:5000/api/auth/logout





### Change password
PUT http://localhost:5000//api/auth/traders/login
Content-Type: application/json

{
  "currentPassword":"123456",
  "newPassword":"12345"
}